name: plugin_mappintelligence
description: Mappintelligence flutter plugin. Based on the tracking data from apps different indicators can be measured, which are already known from the web analytics, such as page impressions, events, screen size, operating system, e-commerce tracking, etc..
version: 0.0.2
author: Stefan Stevanovic <stefan.stevanovic@mapp.com.com>, Aleksandar Marinkovic <aleksandar.marinkovic@mapp.com>, Aleksandar Marinkovic <acamarinkovic93@gmail.com>
homepage: https://github.com/mapp-digital/Mapp-Intelligence-Flutter-Tracking

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.example.plugin_mappintelligence
        pluginClass: PluginMappintelligencePlugin
      ios:
        pluginClass: PluginMappintelligencePlugin


